---
- name: Prepare Skyrim SE / AE with Mod Organizer 2 and SKSE
  hosts: localhost
  connection: local
  gather_facts: true
  roles:
    - install_skyrim_mo2
    - { role: desktop_apps, tags: [desktop] }
